sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t akeel26/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true akeel26/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-624688510171"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY